# .gitlab-ci.yml
# Publish GitLab Pages from parametric-static/ on the main branch only.

stages: [deploy]

pages:
  stage: deploy
  image: alpine:3.19
  script:
    - mkdir -p public
    # copy EVERYTHING (incl. dotfiles) from parametric-static to Pages artifact
    - cp -r parametric-static/. public/
  artifacts:
    paths:
      - public
  only:
    - main
