# .gitlab-ci.yml — publish Pages from parametric-static/ on main
stages: [deploy]

pages:
  stage: deploy
  image: alpine:3.19
  script:
    - mkdir -p public
    - cp -r parametric-static/. public/
  artifacts:
    paths: [ public ]
  only:
    - main
