name: Mirror to GitLab (main only)

on:
  push:
    branches: [ "main" ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: https://gitlab.com/tsukuyomi3/infinite-tsukuyomi.git
          target_repo_token: ${{ secrets.GITLAB_TOKEN }}
