# .github/workflows/mirror-to-gitlab.yml
name: Mirror to GitLab (main only)
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Load your SSH private key from Secrets
      - name: Start ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}

      - name: Trust gitlab.com host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts

      - name: Push main and tags to GitLab (no deletions)
        run: |
          git remote add gitlab git@gitlab.com:infinitetsukuyomi/all-about-disposables.git
          # Push exactly main and tags; no --mirror, no pruning
          git push gitlab HEAD:refs/heads/main --follow-tags
